// <auto-generated />
namespace EShopOS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ShopUpdateOrder_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShopUpdateOrder_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "202102011500125_ShopUpdateOrder_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
